apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gato-gordo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: gato-gordo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gato-gordo-service
            port:
              number: 8080